import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class MenageDrawnImagesService {
  LOAD_PLAN_URL =
    'https://containerdrawingapi-v2.conveyor.cloud/api/drawing/post';

  LOAD_PLAN_URL_LOCAL = 'http://localhost:36023/api/drawing/post';
  constructor(private http: HttpClient) {}

  getLoadPlan(data) {
    // return this.http.post(this.LOAD_PLAN_URL, { ...data }, { responseType: 'blob' })
    // .pipe(
    // catchError(this.handleError('getLoadPlan', data))
    // )

    return {
      containers: [
        {
          id: '40WHC 1',
          name: 'week 41 1',
          length: 12100,
          width: 2420,
          height: 2690,
          maxAllowedVolume: 78768580000,
          maxAllowedWeight: 29370.0,
          loadPlan: {
            id: '10e4a142-41f3-49eb-b05d-9c1bee94d688',
            volumeUsed: 38371588000,
            volumeFree: 40396992000,
            volumeUsedInPercent: 48.71433,
            floorAreaUsed: 28135000,
            floorAreaFree: 1147000,
            floorAreaUsedInPercent: 96.08292,
            lengthUsed: 12100,
            lengthFree: 0,
            lengthUsedInPercent: 100.0,
            widthUsed: 2400,
            widthFree: 20,
            widthUsedInPercent: 99.17355,
            heightUsed: 2100,
            heightFree: 590,
            heightUsedInPercent: 78.06692,
            weightUsed: 8453.721,
            weightFree: 20916.28,
            weightUsedInPercent: 28.783524,
            numberOfPieces: 21,
            loadPlanSteps: [
              {
                id: '84dcc65d-c46e-4593-899b-651625b1fcd9',
                items: [
                  {
                    cargo: {
                      id: '15',
                      name: '92287',
                      length: 5300,
                      width: 1050,
                      height: 1100,
                      weight: 800.0,
                      quantity: 1,
                      cargoStyle: 1,
                      rotatable: false,
                      stackable: true,
                      selfStackable: false,
                      color: 'C4D210',
                      maxLayer: 0,
                      groupId: null,
                      groupName: null,
                    },
                    startX: 0,
                    startY: 0,
                    startZ: 0,
                    orientation: 1,
                    length: 5300,
                    width: 1050,
                    height: 1100,
                    color: 'C4D210',
                  },
                ],
                startX: 0,
                startY: 0,
                startZ: 0,
                length: 5300,
                width: 1050,
                height: 1100,
              },
              {
                id: 'a60568d6-5cd0-425d-b564-ca0a20f1ede1',
                items: [
                  {
                    cargo: {
                      id: '17',
                      name: '92287',
                      length: 4200,
                      width: 800,
                      height: 800,
                      weight: 650.0,
                      quantity: 1,
                      cargoStyle: 1,
                      rotatable: false,
                      stackable: true,
                      selfStackable: false,
                      color: 'F66718',
                      maxLayer: 0,
                      groupId: null,
                      groupName: null,
                    },
                    startX: 0,
                    startY: 1050,
                    startZ: 0,
                    orientation: 1,
                    length: 4200,
                    width: 800,
                    height: 800,
                    color: 'F66718',
                  },
                ],
                startX: 0,
                startY: 1050,
                startZ: 0,
                length: 4200,
                width: 800,
                height: 800,
              },
              {
                id: 'e4d53a00-56a1-461b-9c96-d1c9f2ab264a',
                items: [
                  {
                    cargo: {
                      id: '5',
                      name: '92153',
                      length: 800,
                      width: 1200,
                      height: 2100,
                      weight: 278.2,
                      quantity: 10,
                      cargoStyle: 1,
                      rotatable: false,
                      stackable: false,
                      selfStackable: false,
                      color: 'F49698',
                      maxLayer: 0,
                      groupId: null,
                      groupName: null,
                    },
                    startX: 5300,
                    startY: 0,
                    startZ: 0,
                    orientation: 2,
                    length: 1200,
                    width: 800,
                    height: 2100,
                    color: 'F49698',
                  },
                  {
                    cargo: {
                      id: '5',
                      name: '92153',
                      length: 800,
                      width: 1200,
                      height: 2100,
                      weight: 278.2,
                      quantity: 10,
                      cargoStyle: 1,
                      rotatable: false,
                      stackable: false,
                      selfStackable: false,
                      color: 'F49698',
                      maxLayer: 0,
                      groupId: null,
                      groupName: null,
                    },
                    startX: 5300,
                    startY: 800,
                    startZ: 0,
                    orientation: 2,
                    length: 1200,
                    width: 800,
                    height: 2100,
                    color: 'F49698',
                  },
                  {
                    cargo: {
                      id: '5',
                      name: '92153',
                      length: 800,
                      width: 1200,
                      height: 2100,
                      weight: 278.2,
                      quantity: 10,
                      cargoStyle: 1,
                      rotatable: false,
                      stackable: false,
                      selfStackable: false,
                      color: 'F49698',
                      maxLayer: 0,
                      groupId: null,
                      groupName: null,
                    },
                    startX: 5300,
                    startY: 1600,
                    startZ: 0,
                    orientation: 2,
                    length: 1200,
                    width: 800,
                    height: 2100,
                    color: 'F49698',
                  },
                ],
                startX: 5300,
                startY: 0,
                startZ: 0,
                length: 1200,
                width: 2400,
                height: 2100,
              },
              {
                id: 'baac8b18-45de-4970-8950-7ade3796ade5',
                items: [
                  {
                    cargo: {
                      id: '5',
                      name: '92153',
                      length: 800,
                      width: 1200,
                      height: 2100,
                      weight: 278.2,
                      quantity: 10,
                      cargoStyle: 1,
                      rotatable: false,
                      stackable: false,
                      selfStackable: false,
                      color: 'F49698',
                      maxLayer: 0,
                      groupId: null,
                      groupName: null,
                    },
                    startX: 6500,
                    startY: 0,
                    startZ: 0,
                    orientation: 2,
                    length: 1200,
                    width: 800,
                    height: 2100,
                    color: 'F49698',
                  },
                  {
                    cargo: {
                      id: '5',
                      name: '92153',
                      length: 800,
                      width: 1200,
                      height: 2100,
                      weight: 278.2,
                      quantity: 10,
                      cargoStyle: 1,
                      rotatable: false,
                      stackable: false,
                      selfStackable: false,
                      color: 'F49698',
                      maxLayer: 0,
                      groupId: null,
                      groupName: null,
                    },
                    startX: 6500,
                    startY: 800,
                    startZ: 0,
                    orientation: 2,
                    length: 1200,
                    width: 800,
                    height: 2100,
                    color: 'F49698',
                  },
                  {
                    cargo: {
                      id: '5',
                      name: '92153',
                      length: 800,
                      width: 1200,
                      height: 2100,
                      weight: 278.2,
                      quantity: 10,
                      cargoStyle: 1,
                      rotatable: false,
                      stackable: false,
                      selfStackable: false,
                      color: 'F49698',
                      maxLayer: 0,
                      groupId: null,
                      groupName: null,
                    },
                    startX: 6500,
                    startY: 1600,
                    startZ: 0,
                    orientation: 2,
                    length: 1200,
                    width: 800,
                    height: 2100,
                    color: 'F49698',
                  },
                ],
                startX: 6500,
                startY: 0,
                startZ: 0,
                length: 1200,
                width: 2400,
                height: 2100,
              },
              {
                id: '8b614b44-a5a7-4a1a-908d-595b7d4853ab',
                items: [
                  {
                    cargo: {
                      id: '5',
                      name: '92153',
                      length: 800,
                      width: 1200,
                      height: 2100,
                      weight: 278.2,
                      quantity: 10,
                      cargoStyle: 1,
                      rotatable: false,
                      stackable: false,
                      selfStackable: false,
                      color: 'F49698',
                      maxLayer: 0,
                      groupId: null,
                      groupName: null,
                    },
                    startX: 7700,
                    startY: 0,
                    startZ: 0,
                    orientation: 2,
                    length: 1200,
                    width: 800,
                    height: 2100,
                    color: 'F49698',
                  },
                  {
                    cargo: {
                      id: '5',
                      name: '92153',
                      length: 800,
                      width: 1200,
                      height: 2100,
                      weight: 278.2,
                      quantity: 10,
                      cargoStyle: 1,
                      rotatable: false,
                      stackable: false,
                      selfStackable: false,
                      color: 'F49698',
                      maxLayer: 0,
                      groupId: null,
                      groupName: null,
                    },
                    startX: 7700,
                    startY: 800,
                    startZ: 0,
                    orientation: 2,
                    length: 1200,
                    width: 800,
                    height: 2100,
                    color: 'F49698',
                  },
                  {
                    cargo: {
                      id: '5',
                      name: '92153',
                      length: 800,
                      width: 1200,
                      height: 2100,
                      weight: 278.2,
                      quantity: 10,
                      cargoStyle: 1,
                      rotatable: false,
                      stackable: false,
                      selfStackable: false,
                      color: 'F49698',
                      maxLayer: 0,
                      groupId: null,
                      groupName: null,
                    },
                    startX: 7700,
                    startY: 1600,
                    startZ: 0,
                    orientation: 2,
                    length: 1200,
                    width: 800,
                    height: 2100,
                    color: 'F49698',
                  },
                ],
                startX: 7700,
                startY: 0,
                startZ: 0,
                length: 1200,
                width: 2400,
                height: 2100,
              },
              {
                id: 'e35b77f8-913b-48fd-989e-c35facb243c5',
                items: [
                  {
                    cargo: {
                      id: '12',
                      name: '91315',
                      length: 1200,
                      width: 1200,
                      height: 980,
                      weight: 950.0,
                      quantity: 3,
                      cargoStyle: 1,
                      rotatable: false,
                      stackable: false,
                      selfStackable: false,
                      color: '07D380',
                      maxLayer: 0,
                      groupId: null,
                      groupName: null,
                    },
                    startX: 8900,
                    startY: 0,
                    startZ: 0,
                    orientation: 1,
                    length: 1200,
                    width: 1200,
                    height: 980,
                    color: '07D380',
                  },
                  {
                    cargo: {
                      id: '12',
                      name: '91315',
                      length: 1200,
                      width: 1200,
                      height: 980,
                      weight: 950.0,
                      quantity: 3,
                      cargoStyle: 1,
                      rotatable: false,
                      stackable: false,
                      selfStackable: false,
                      color: '07D380',
                      maxLayer: 0,
                      groupId: null,
                      groupName: null,
                    },
                    startX: 8900,
                    startY: 1200,
                    startZ: 0,
                    orientation: 1,
                    length: 1200,
                    width: 1200,
                    height: 980,
                    color: '07D380',
                  },
                ],
                startX: 8900,
                startY: 0,
                startZ: 0,
                length: 1200,
                width: 2400,
                height: 980,
              },
              {
                id: '6fefd018-79b3-440a-93d7-8edb7ea25ecb',
                items: [
                  {
                    cargo: {
                      id: '18',
                      name: '92287',
                      length: 5300,
                      width: 500,
                      height: 900,
                      weight: 700.0,
                      quantity: 1,
                      cargoStyle: 1,
                      rotatable: false,
                      stackable: true,
                      selfStackable: false,
                      color: 'BE9FEB',
                      maxLayer: 0,
                      groupId: null,
                      groupName: null,
                    },
                    startX: 0,
                    startY: 1850,
                    startZ: 0,
                    orientation: 1,
                    length: 5300,
                    width: 500,
                    height: 900,
                    color: 'BE9FEB',
                  },
                ],
                startX: 0,
                startY: 1850,
                startZ: 0,
                length: 5300,
                width: 500,
                height: 900,
              },
              {
                id: '889dc437-c20c-4888-9bac-efd68c254105',
                items: [
                  {
                    cargo: {
                      id: '12',
                      name: '91315',
                      length: 1200,
                      width: 1200,
                      height: 980,
                      weight: 950.0,
                      quantity: 3,
                      cargoStyle: 1,
                      rotatable: false,
                      stackable: false,
                      selfStackable: false,
                      color: '07D380',
                      maxLayer: 0,
                      groupId: null,
                      groupName: null,
                    },
                    startX: 10100,
                    startY: 1050,
                    startZ: 0,
                    orientation: 1,
                    length: 1200,
                    width: 1200,
                    height: 980,
                    color: '07D380',
                  },
                ],
                startX: 10100,
                startY: 1050,
                startZ: 0,
                length: 1200,
                width: 1200,
                height: 980,
              },
              {
                id: '6524142d-a9bb-4b33-a3fb-492bbb4152a5',
                items: [
                  {
                    cargo: {
                      id: '16',
                      name: '92287',
                      length: 1200,
                      width: 800,
                      height: 600,
                      weight: 295.97,
                      quantity: 1,
                      cargoStyle: 1,
                      rotatable: false,
                      stackable: true,
                      selfStackable: false,
                      color: '3CAFBE',
                      maxLayer: 0,
                      groupId: null,
                      groupName: null,
                    },
                    startX: 11300,
                    startY: 1050,
                    startZ: 0,
                    orientation: 2,
                    length: 800,
                    width: 1200,
                    height: 600,
                    color: '3CAFBE',
                  },
                ],
                startX: 11300,
                startY: 1050,
                startZ: 0,
                length: 800,
                width: 1200,
                height: 600,
              },
              {
                id: '4a46834b-ccf7-4a1c-932d-802c246a48d6',
                items: [
                  {
                    cargo: {
                      id: '5',
                      name: '92153',
                      length: 800,
                      width: 1200,
                      height: 2100,
                      weight: 278.2,
                      quantity: 10,
                      cargoStyle: 1,
                      rotatable: false,
                      stackable: false,
                      selfStackable: false,
                      color: 'F49698',
                      maxLayer: 0,
                      groupId: null,
                      groupName: null,
                    },
                    startX: 10100,
                    startY: 0,
                    startZ: 0,
                    orientation: 2,
                    length: 1200,
                    width: 800,
                    height: 2100,
                    color: 'F49698',
                  },
                ],
                startX: 10100,
                startY: 0,
                startZ: 0,
                length: 1200,
                width: 800,
                height: 2100,
              },
              {
                id: '52846d32-ce8e-45bb-9390-3e67fb5b2317',
                items: [
                  {
                    cargo: {
                      id: '22',
                      name: '92234',
                      length: 800,
                      width: 1100,
                      height: 620,
                      weight: 215.0,
                      quantity: 1,
                      cargoStyle: 1,
                      rotatable: false,
                      stackable: false,
                      selfStackable: false,
                      color: 'BAB5F5',
                      maxLayer: 0,
                      groupId: null,
                      groupName: null,
                    },
                    startX: 4200,
                    startY: 1050,
                    startZ: 0,
                    orientation: 2,
                    length: 1100,
                    width: 800,
                    height: 620,
                    color: 'BAB5F5',
                  },
                ],
                startX: 4200,
                startY: 1050,
                startZ: 0,
                length: 1100,
                width: 800,
                height: 620,
              },
              {
                id: 'e66cf2a7-b186-456b-9a45-bceeaaca7af7',
                items: [
                  {
                    cargo: {
                      id: '4',
                      name: '92131',
                      length: 800,
                      width: 1000,
                      height: 1480,
                      weight: 87.0,
                      quantity: 1,
                      cargoStyle: 1,
                      rotatable: false,
                      stackable: false,
                      selfStackable: false,
                      color: '75c273',
                      maxLayer: 0,
                      groupId: null,
                      groupName: null,
                    },
                    startX: 11300,
                    startY: 0,
                    startZ: 0,
                    orientation: 1,
                    length: 800,
                    width: 1000,
                    height: 1480,
                    color: '75c273',
                  },
                ],
                startX: 11300,
                startY: 0,
                startZ: 0,
                length: 800,
                width: 1000,
                height: 1480,
              },
              {
                id: 'e7c17a61-c8e9-42f8-a8b1-ca6505e522c7',
                items: [
                  {
                    cargo: {
                      id: '10',
                      name: '92276',
                      length: 600,
                      width: 800,
                      height: 500,
                      weight: 38.0,
                      quantity: 1,
                      cargoStyle: 0,
                      rotatable: false,
                      stackable: false,
                      selfStackable: false,
                      color: 'e4467d',
                      maxLayer: 0,
                      groupId: null,
                      groupName: null,
                    },
                    startX: 4200,
                    startY: 1050,
                    startZ: 620,
                    orientation: 1,
                    length: 600,
                    width: 800,
                    height: 500,
                    color: 'e4467d',
                  },
                ],
                startX: 4200,
                startY: 1050,
                startZ: 620,
                length: 600,
                width: 800,
                height: 500,
              },
              {
                id: '9141a92d-0c5e-487e-b18a-057aea612f91',
                items: [
                  {
                    cargo: {
                      id: '11',
                      name: '92276',
                      length: 560,
                      width: 720,
                      height: 590,
                      weight: 35.75,
                      quantity: 1,
                      cargoStyle: 0,
                      rotatable: false,
                      stackable: false,
                      selfStackable: false,
                      color: 'af158d',
                      maxLayer: 0,
                      groupId: null,
                      groupName: null,
                    },
                    startX: 4200,
                    startY: 1050,
                    startZ: 1120,
                    orientation: 1,
                    length: 560,
                    width: 720,
                    height: 590,
                    color: 'af158d',
                  },
                ],
                startX: 4200,
                startY: 1050,
                startZ: 1120,
                length: 560,
                width: 720,
                height: 590,
              },
            ],
            items: [
              {
                id: '15',
                name: '92287',
                length: 5300,
                width: 1050,
                height: 1100,
                weight: 800.0,
                quantity: 1,
                cargoStyle: 1,
                rotatable: false,
                stackable: true,
                selfStackable: false,
                color: 'C4D210',
                maxLayer: 0,
                groupId: '13',
                groupName: '92287',
              },
              {
                id: '17',
                name: '92287',
                length: 4200,
                width: 800,
                height: 800,
                weight: 650.0,
                quantity: 1,
                cargoStyle: 1,
                rotatable: false,
                stackable: true,
                selfStackable: false,
                color: 'F66718',
                maxLayer: 0,
                groupId: '13',
                groupName: '92287',
              },
              {
                id: '5',
                name: '92153',
                length: 800,
                width: 1200,
                height: 2100,
                weight: 278.2,
                quantity: 10,
                cargoStyle: 1,
                rotatable: false,
                stackable: false,
                selfStackable: false,
                color: 'F49698',
                maxLayer: 0,
                groupId: '5',
                groupName: '92153',
              },
              {
                id: '12',
                name: '91315',
                length: 1200,
                width: 1200,
                height: 980,
                weight: 950.0,
                quantity: 3,
                cargoStyle: 1,
                rotatable: false,
                stackable: false,
                selfStackable: false,
                color: '07D380',
                maxLayer: 0,
                groupId: '10',
                groupName: '91315',
              },
              {
                id: '18',
                name: '92287',
                length: 5300,
                width: 500,
                height: 900,
                weight: 700.0,
                quantity: 1,
                cargoStyle: 1,
                rotatable: false,
                stackable: true,
                selfStackable: false,
                color: 'BE9FEB',
                maxLayer: 0,
                groupId: '13',
                groupName: '92287',
              },
              {
                id: '16',
                name: '92287',
                length: 1200,
                width: 800,
                height: 600,
                weight: 295.97,
                quantity: 1,
                cargoStyle: 1,
                rotatable: false,
                stackable: true,
                selfStackable: false,
                color: '3CAFBE',
                maxLayer: 0,
                groupId: '13',
                groupName: '92287',
              },
              {
                id: '22',
                name: '92234',
                length: 800,
                width: 1100,
                height: 620,
                weight: 215.0,
                quantity: 1,
                cargoStyle: 1,
                rotatable: false,
                stackable: false,
                selfStackable: false,
                color: 'BAB5F5',
                maxLayer: 0,
                groupId: '16',
                groupName: '92234',
              },
              {
                id: '4',
                name: '92131',
                length: 800,
                width: 1000,
                height: 1480,
                weight: 87.0,
                quantity: 1,
                cargoStyle: 1,
                rotatable: false,
                stackable: false,
                selfStackable: false,
                color: '75c273',
                maxLayer: 0,
                groupId: '4',
                groupName: '92131',
              },
              {
                id: '10',
                name: '92276',
                length: 600,
                width: 800,
                height: 500,
                weight: 38.0,
                quantity: 1,
                cargoStyle: 0,
                rotatable: false,
                stackable: false,
                selfStackable: false,
                color: 'e4467d',
                maxLayer: 0,
                groupId: '9',
                groupName: '92276',
              },
              {
                id: '11',
                name: '92276',
                length: 560,
                width: 720,
                height: 590,
                weight: 35.75,
                quantity: 1,
                cargoStyle: 0,
                rotatable: false,
                stackable: false,
                selfStackable: false,
                color: 'af158d',
                maxLayer: 0,
                groupId: '9',
                groupName: '92276',
              },
            ],
          },
        },
        {
          id: '40HC 2',
          name: 'week 41 2',
          length: 12000,
          width: 2350,
          height: 2690,
          maxAllowedVolume: 75858000000,
          maxAllowedWeight: 28600.0,
          loadPlan: {
            id: '79462af8-5aa0-490c-9a7a-06515ff4865a',
            volumeUsed: 26056000000,
            volumeFree: 49802000000,
            volumeUsedInPercent: 34.348385,
            floorAreaUsed: 19610000,
            floorAreaFree: 8590000,
            floorAreaUsedInPercent: 69.539,
            lengthUsed: 11250,
            lengthFree: 750,
            lengthUsedInPercent: 93.75,
            widthUsed: 2200,
            widthFree: 150,
            widthUsedInPercent: 93.61702,
            heightUsed: 2550,
            heightFree: 140,
            heightUsedInPercent: 94.79554,
            weightUsed: 8138.9,
            weightFree: 20461.1,
            weightUsedInPercent: 28.457693,
            numberOfPieces: 23,
            loadPlanSteps: [
              {
                id: 'e970e5a1-98e2-4dc7-9635-a88f6633f19e',
                items: [
                  {
                    cargo: {
                      id: '14',
                      name: '92309',
                      length: 2500,
                      width: 1000,
                      height: 1250,
                      weight: 1200.0,
                      quantity: 1,
                      cargoStyle: 1,
                      rotatable: false,
                      stackable: true,
                      selfStackable: false,
                      color: '57f3c5',
                      maxLayer: 0,
                      groupId: null,
                      groupName: null,
                    },
                    startX: 0,
                    startY: 0,
                    startZ: 0,
                    orientation: 1,
                    length: 2500,
                    width: 1000,
                    height: 1250,
                    color: '57f3c5',
                  },
                ],
                startX: 0,
                startY: 0,
                startZ: 0,
                length: 2500,
                width: 1000,
                height: 1250,
              },
              {
                id: 'a04e2af7-284f-42c4-ba53-287c8e24177d',
                items: [
                  {
                    cargo: {
                      id: '24',
                      name: '92253',
                      length: 1900,
                      width: 1200,
                      height: 1100,
                      weight: 200.0,
                      quantity: 1,
                      cargoStyle: 1,
                      rotatable: false,
                      stackable: false,
                      selfStackable: false,
                      color: 'f6dc7a',
                      maxLayer: 0,
                      groupId: null,
                      groupName: null,
                    },
                    startX: 2500,
                    startY: 0,
                    startZ: 0,
                    orientation: 2,
                    length: 1200,
                    width: 1900,
                    height: 1100,
                    color: 'f6dc7a',
                  },
                ],
                startX: 2500,
                startY: 0,
                startZ: 0,
                length: 1200,
                width: 1900,
                height: 1100,
              },
              {
                id: '439e733f-3b39-460e-ac6a-30c86d19cc64',
                items: [
                  {
                    cargo: {
                      id: '23',
                      name: '92252',
                      length: 2500,
                      width: 900,
                      height: 1300,
                      weight: 372.0,
                      quantity: 1,
                      cargoStyle: 1,
                      rotatable: false,
                      stackable: false,
                      selfStackable: false,
                      color: 'd7f4b2',
                      maxLayer: 0,
                      groupId: null,
                      groupName: null,
                    },
                    startX: 0,
                    startY: 0,
                    startZ: 1250,
                    orientation: 1,
                    length: 2500,
                    width: 900,
                    height: 1300,
                    color: 'd7f4b2',
                  },
                ],
                startX: 0,
                startY: 0,
                startZ: 1250,
                length: 2500,
                width: 900,
                height: 1300,
              },
              {
                id: '45454082-dfc1-4b84-b221-1c62fe4ea9d7',
                items: [
                  {
                    cargo: {
                      id: '7',
                      name: '92155',
                      length: 1250,
                      width: 800,
                      height: 600,
                      weight: 640.0,
                      quantity: 2,
                      cargoStyle: 1,
                      rotatable: false,
                      stackable: false,
                      selfStackable: false,
                      color: 'a9adae',
                      maxLayer: 0,
                      groupId: null,
                      groupName: null,
                    },
                    startX: 3700,
                    startY: 0,
                    startZ: 0,
                    orientation: 1,
                    length: 1250,
                    width: 800,
                    height: 600,
                    color: 'a9adae',
                  },
                  {
                    cargo: {
                      id: '7',
                      name: '92155',
                      length: 1250,
                      width: 800,
                      height: 600,
                      weight: 640.0,
                      quantity: 2,
                      cargoStyle: 1,
                      rotatable: false,
                      stackable: false,
                      selfStackable: false,
                      color: 'a9adae',
                      maxLayer: 0,
                      groupId: null,
                      groupName: null,
                    },
                    startX: 3700,
                    startY: 800,
                    startZ: 0,
                    orientation: 1,
                    length: 1250,
                    width: 800,
                    height: 600,
                    color: 'a9adae',
                  },
                ],
                startX: 3700,
                startY: 0,
                startZ: 0,
                length: 1250,
                width: 1600,
                height: 600,
              },
              {
                id: '577798cc-dd88-411c-b812-cb8f1a072c77',
                items: [
                  {
                    cargo: {
                      id: '2',
                      name: '92141',
                      length: 1200,
                      width: 800,
                      height: 900,
                      weight: 149.86,
                      quantity: 1,
                      cargoStyle: 1,
                      rotatable: false,
                      stackable: false,
                      selfStackable: false,
                      color: '20af1a',
                      maxLayer: 0,
                      groupId: null,
                      groupName: null,
                    },
                    startX: 4950,
                    startY: 0,
                    startZ: 0,
                    orientation: 1,
                    length: 1200,
                    width: 800,
                    height: 900,
                    color: '20af1a',
                  },
                  {
                    cargo: {
                      id: '20',
                      name: '91548',
                      length: 800,
                      width: 1200,
                      height: 900,
                      weight: 200.0,
                      quantity: 1,
                      cargoStyle: 1,
                      rotatable: false,
                      stackable: false,
                      selfStackable: false,
                      color: '7938d6',
                      maxLayer: 0,
                      groupId: null,
                      groupName: null,
                    },
                    startX: 4950,
                    startY: 800,
                    startZ: 0,
                    orientation: 2,
                    length: 1200,
                    width: 800,
                    height: 900,
                    color: '7938d6',
                  },
                ],
                startX: 4950,
                startY: 0,
                startZ: 0,
                length: 1200,
                width: 1600,
                height: 900,
              },
              {
                id: 'ab5969d3-dd05-41dd-be54-3379277c9804',
                items: [
                  {
                    cargo: {
                      id: '13',
                      name: '92256',
                      length: 800,
                      width: 1200,
                      height: 1160,
                      weight: 341.67,
                      quantity: 6,
                      cargoStyle: 1,
                      rotatable: false,
                      stackable: false,
                      selfStackable: false,
                      color: 'b97fcf',
                      maxLayer: 0,
                      groupId: null,
                      groupName: null,
                    },
                    startX: 6150,
                    startY: 0,
                    startZ: 0,
                    orientation: 2,
                    length: 1200,
                    width: 800,
                    height: 1160,
                    color: 'b97fcf',
                  },
                  {
                    cargo: {
                      id: '13',
                      name: '92256',
                      length: 800,
                      width: 1200,
                      height: 1160,
                      weight: 341.67,
                      quantity: 6,
                      cargoStyle: 1,
                      rotatable: false,
                      stackable: false,
                      selfStackable: false,
                      color: 'b97fcf',
                      maxLayer: 0,
                      groupId: null,
                      groupName: null,
                    },
                    startX: 6150,
                    startY: 800,
                    startZ: 0,
                    orientation: 2,
                    length: 1200,
                    width: 800,
                    height: 1160,
                    color: 'b97fcf',
                  },
                ],
                startX: 6150,
                startY: 0,
                startZ: 0,
                length: 1200,
                width: 1600,
                height: 1160,
              },
              {
                id: '567105ea-f6b9-4bcf-8002-f7b6efb465b8',
                items: [
                  {
                    cargo: {
                      id: '13',
                      name: '92256',
                      length: 800,
                      width: 1200,
                      height: 1160,
                      weight: 341.67,
                      quantity: 6,
                      cargoStyle: 1,
                      rotatable: false,
                      stackable: false,
                      selfStackable: false,
                      color: 'b97fcf',
                      maxLayer: 0,
                      groupId: null,
                      groupName: null,
                    },
                    startX: 7350,
                    startY: 0,
                    startZ: 0,
                    orientation: 2,
                    length: 1200,
                    width: 800,
                    height: 1160,
                    color: 'b97fcf',
                  },
                  {
                    cargo: {
                      id: '13',
                      name: '92256',
                      length: 800,
                      width: 1200,
                      height: 1160,
                      weight: 341.67,
                      quantity: 6,
                      cargoStyle: 1,
                      rotatable: false,
                      stackable: false,
                      selfStackable: false,
                      color: 'b97fcf',
                      maxLayer: 0,
                      groupId: null,
                      groupName: null,
                    },
                    startX: 7350,
                    startY: 800,
                    startZ: 0,
                    orientation: 2,
                    length: 1200,
                    width: 800,
                    height: 1160,
                    color: 'b97fcf',
                  },
                ],
                startX: 7350,
                startY: 0,
                startZ: 0,
                length: 1200,
                width: 1600,
                height: 1160,
              },
              {
                id: 'f68f9345-9dd5-4428-91f3-4cb52b90cc7b',
                items: [
                  {
                    cargo: {
                      id: '13',
                      name: '92256',
                      length: 800,
                      width: 1200,
                      height: 1160,
                      weight: 341.67,
                      quantity: 6,
                      cargoStyle: 1,
                      rotatable: false,
                      stackable: false,
                      selfStackable: false,
                      color: 'b97fcf',
                      maxLayer: 0,
                      groupId: null,
                      groupName: null,
                    },
                    startX: 8550,
                    startY: 0,
                    startZ: 0,
                    orientation: 2,
                    length: 1200,
                    width: 800,
                    height: 1160,
                    color: 'b97fcf',
                  },
                  {
                    cargo: {
                      id: '13',
                      name: '92256',
                      length: 800,
                      width: 1200,
                      height: 1160,
                      weight: 341.67,
                      quantity: 6,
                      cargoStyle: 1,
                      rotatable: false,
                      stackable: false,
                      selfStackable: false,
                      color: 'b97fcf',
                      maxLayer: 0,
                      groupId: null,
                      groupName: null,
                    },
                    startX: 8550,
                    startY: 800,
                    startZ: 0,
                    orientation: 2,
                    length: 1200,
                    width: 800,
                    height: 1160,
                    color: 'b97fcf',
                  },
                ],
                startX: 8550,
                startY: 0,
                startZ: 0,
                length: 1200,
                width: 1600,
                height: 1160,
              },
              {
                id: '4fd0011a-7506-4a92-980e-089b035c3ae6',
                items: [
                  {
                    cargo: {
                      id: '9',
                      name: '91083',
                      length: 2100,
                      width: 700,
                      height: 1400,
                      weight: 230.0,
                      quantity: 1,
                      cargoStyle: 1,
                      rotatable: false,
                      stackable: false,
                      selfStackable: false,
                      color: 'f6c41b',
                      maxLayer: 0,
                      groupId: null,
                      groupName: null,
                    },
                    startX: 9750,
                    startY: 0,
                    startZ: 0,
                    orientation: 2,
                    length: 700,
                    width: 2100,
                    height: 1400,
                    color: 'f6c41b',
                  },
                ],
                startX: 9750,
                startY: 0,
                startZ: 0,
                length: 700,
                width: 2100,
                height: 1400,
              },
              {
                id: 'd2d5911a-619a-4222-905b-2c594be7b6e2',
                items: [
                  {
                    cargo: {
                      id: '8',
                      name: '91083',
                      length: 1800,
                      width: 800,
                      height: 1200,
                      weight: 200.0,
                      quantity: 1,
                      cargoStyle: 1,
                      rotatable: false,
                      stackable: false,
                      selfStackable: false,
                      color: '63F563',
                      maxLayer: 0,
                      groupId: null,
                      groupName: null,
                    },
                    startX: 10450,
                    startY: 0,
                    startZ: 0,
                    orientation: 2,
                    length: 800,
                    width: 1800,
                    height: 1200,
                    color: '63F563',
                  },
                ],
                startX: 10450,
                startY: 0,
                startZ: 0,
                length: 800,
                width: 1800,
                height: 1200,
              },
              {
                id: '05ea9e1e-d47d-49b7-b9f8-8f449134d48e',
                items: [
                  {
                    cargo: {
                      id: '19',
                      name: '91548',
                      length: 800,
                      width: 1200,
                      height: 650,
                      weight: 174.0,
                      quantity: 1,
                      cargoStyle: 1,
                      rotatable: false,
                      stackable: true,
                      selfStackable: false,
                      color: 'F0EEA0',
                      maxLayer: 0,
                      groupId: null,
                      groupName: null,
                    },
                    startX: 0,
                    startY: 1000,
                    startZ: 0,
                    orientation: 1,
                    length: 800,
                    width: 1200,
                    height: 650,
                    color: 'F0EEA0',
                  },
                ],
                startX: 0,
                startY: 1000,
                startZ: 0,
                length: 800,
                width: 1200,
                height: 650,
              },
              {
                id: '87ff72f9-d54b-44b0-8211-c0f5f9282894',
                items: [
                  {
                    cargo: {
                      id: '1',
                      name: '92140',
                      length: 1200,
                      width: 800,
                      height: 670,
                      weight: 122.0,
                      quantity: 1,
                      cargoStyle: 1,
                      rotatable: false,
                      stackable: true,
                      selfStackable: false,
                      color: 'FFE5E9',
                      maxLayer: 0,
                      groupId: null,
                      groupName: null,
                    },
                    startX: 0,
                    startY: 1000,
                    startZ: 650,
                    orientation: 2,
                    length: 800,
                    width: 1200,
                    height: 670,
                    color: 'FFE5E9',
                  },
                ],
                startX: 0,
                startY: 1000,
                startZ: 650,
                length: 800,
                width: 1200,
                height: 670,
              },
              {
                id: '1e9f5e28-5edc-4281-8b94-76a98d125b96',
                items: [
                  {
                    cargo: {
                      id: '6',
                      name: '92145',
                      length: 800,
                      width: 1200,
                      height: 1000,
                      weight: 86.0,
                      quantity: 1,
                      cargoStyle: 1,
                      rotatable: false,
                      stackable: false,
                      selfStackable: false,
                      color: 'AD292C',
                      maxLayer: 0,
                      groupId: null,
                      groupName: null,
                    },
                    startX: 0,
                    startY: 900,
                    startZ: 1320,
                    orientation: 1,
                    length: 800,
                    width: 1200,
                    height: 1000,
                    color: 'AD292C',
                  },
                ],
                startX: 0,
                startY: 900,
                startZ: 1320,
                length: 800,
                width: 1200,
                height: 1000,
              },
              {
                id: '1b0e63d5-b314-494a-ba98-6d644cd80ea0',
                items: [
                  {
                    cargo: {
                      id: '3',
                      name: '92144',
                      length: 500,
                      width: 320,
                      height: 460,
                      weight: 10.0,
                      quantity: 2,
                      cargoStyle: 0,
                      rotatable: false,
                      stackable: true,
                      selfStackable: false,
                      color: '7aa8d5',
                      maxLayer: 0,
                      groupId: null,
                      groupName: null,
                    },
                    startX: 800,
                    startY: 1000,
                    startZ: 0,
                    orientation: 2,
                    length: 320,
                    width: 500,
                    height: 460,
                    color: '7aa8d5',
                  },
                  {
                    cargo: {
                      id: '3',
                      name: '92144',
                      length: 500,
                      width: 320,
                      height: 460,
                      weight: 10.0,
                      quantity: 2,
                      cargoStyle: 0,
                      rotatable: false,
                      stackable: true,
                      selfStackable: false,
                      color: '7aa8d5',
                      maxLayer: 0,
                      groupId: null,
                      groupName: null,
                    },
                    startX: 800,
                    startY: 1500,
                    startZ: 0,
                    orientation: 2,
                    length: 320,
                    width: 500,
                    height: 460,
                    color: '7aa8d5',
                  },
                ],
                startX: 800,
                startY: 1000,
                startZ: 0,
                length: 320,
                width: 1000,
                height: 460,
              },
              {
                id: 'dabcb113-7476-44a3-9bb4-3c6766d1cbb6',
                items: [
                  {
                    cargo: {
                      id: '21',
                      name: '92295',
                      length: 1200,
                      width: 800,
                      height: 600,
                      weight: 618.34,
                      quantity: 3,
                      cargoStyle: 1,
                      rotatable: false,
                      stackable: false,
                      selfStackable: true,
                      color: '507BD0',
                      maxLayer: 2,
                      groupId: null,
                      groupName: null,
                    },
                    startX: 1120,
                    startY: 1000,
                    startZ: 0,
                    orientation: 1,
                    length: 1200,
                    width: 800,
                    height: 600,
                    color: '507BD0',
                  },
                  {
                    cargo: {
                      id: '21',
                      name: '92295',
                      length: 1200,
                      width: 800,
                      height: 600,
                      weight: 618.34,
                      quantity: 3,
                      cargoStyle: 1,
                      rotatable: false,
                      stackable: false,
                      selfStackable: true,
                      color: '507BD0',
                      maxLayer: 2,
                      groupId: null,
                      groupName: null,
                    },
                    startX: 1120,
                    startY: 1000,
                    startZ: 600,
                    orientation: 1,
                    length: 1200,
                    width: 800,
                    height: 600,
                    color: '507BD0',
                  },
                ],
                startX: 1120,
                startY: 1000,
                startZ: 0,
                length: 1200,
                width: 800,
                height: 1200,
              },
              {
                id: '9f73b5a8-48a4-4890-b901-b2964e0ae793',
                items: [
                  {
                    cargo: {
                      id: '21',
                      name: '92295',
                      length: 1200,
                      width: 800,
                      height: 600,
                      weight: 618.34,
                      quantity: 3,
                      cargoStyle: 1,
                      rotatable: false,
                      stackable: false,
                      selfStackable: true,
                      color: '507BD0',
                      maxLayer: 2,
                      groupId: null,
                      groupName: null,
                    },
                    startX: 1120,
                    startY: 1000,
                    startZ: 1200,
                    orientation: 1,
                    length: 1200,
                    width: 800,
                    height: 600,
                    color: '507BD0',
                  },
                ],
                startX: 1120,
                startY: 1000,
                startZ: 1200,
                length: 1200,
                width: 800,
                height: 600,
              },
            ],
            items: [
              {
                id: '14',
                name: '92309',
                length: 2500,
                width: 1000,
                height: 1250,
                weight: 1200.0,
                quantity: 1,
                cargoStyle: 1,
                rotatable: false,
                stackable: true,
                selfStackable: false,
                color: '57f3c5',
                maxLayer: 0,
                groupId: '12',
                groupName: '92309',
              },
              {
                id: '24',
                name: '92253',
                length: 1900,
                width: 1200,
                height: 1100,
                weight: 200.0,
                quantity: 1,
                cargoStyle: 1,
                rotatable: false,
                stackable: false,
                selfStackable: false,
                color: 'f6dc7a',
                maxLayer: 0,
                groupId: '18',
                groupName: '92253',
              },
              {
                id: '23',
                name: '92252',
                length: 2500,
                width: 900,
                height: 1300,
                weight: 372.0,
                quantity: 1,
                cargoStyle: 1,
                rotatable: false,
                stackable: false,
                selfStackable: false,
                color: 'd7f4b2',
                maxLayer: 0,
                groupId: '17',
                groupName: '92252',
              },
              {
                id: '7',
                name: '92155',
                length: 1250,
                width: 800,
                height: 600,
                weight: 640.0,
                quantity: 2,
                cargoStyle: 1,
                rotatable: false,
                stackable: false,
                selfStackable: false,
                color: 'a9adae',
                maxLayer: 0,
                groupId: '7',
                groupName: '92155',
              },
              {
                id: '2',
                name: '92141',
                length: 1200,
                width: 800,
                height: 900,
                weight: 149.86,
                quantity: 1,
                cargoStyle: 1,
                rotatable: false,
                stackable: false,
                selfStackable: false,
                color: '20af1a',
                maxLayer: 0,
                groupId: '2',
                groupName: '92141',
              },
              {
                id: '20',
                name: '91548',
                length: 800,
                width: 1200,
                height: 900,
                weight: 200.0,
                quantity: 1,
                cargoStyle: 1,
                rotatable: false,
                stackable: false,
                selfStackable: false,
                color: '7938d6',
                maxLayer: 0,
                groupId: '14',
                groupName: '91548',
              },
              {
                id: '13',
                name: '92256',
                length: 800,
                width: 1200,
                height: 1160,
                weight: 341.67,
                quantity: 6,
                cargoStyle: 1,
                rotatable: false,
                stackable: false,
                selfStackable: false,
                color: 'b97fcf',
                maxLayer: 0,
                groupId: '11',
                groupName: '92256',
              },
              {
                id: '9',
                name: '91083',
                length: 2100,
                width: 700,
                height: 1400,
                weight: 230.0,
                quantity: 1,
                cargoStyle: 1,
                rotatable: false,
                stackable: false,
                selfStackable: false,
                color: 'f6c41b',
                maxLayer: 0,
                groupId: '8',
                groupName: '91083',
              },
              {
                id: '8',
                name: '91083',
                length: 1800,
                width: 800,
                height: 1200,
                weight: 200.0,
                quantity: 1,
                cargoStyle: 1,
                rotatable: false,
                stackable: false,
                selfStackable: false,
                color: '63F563',
                maxLayer: 0,
                groupId: '8',
                groupName: '91083',
              },
              {
                id: '19',
                name: '91548',
                length: 800,
                width: 1200,
                height: 650,
                weight: 174.0,
                quantity: 1,
                cargoStyle: 1,
                rotatable: false,
                stackable: true,
                selfStackable: false,
                color: 'F0EEA0',
                maxLayer: 0,
                groupId: '14',
                groupName: '91548',
              },
              {
                id: '1',
                name: '92140',
                length: 1200,
                width: 800,
                height: 670,
                weight: 122.0,
                quantity: 1,
                cargoStyle: 1,
                rotatable: false,
                stackable: true,
                selfStackable: false,
                color: 'FFE5E9',
                maxLayer: 0,
                groupId: '1',
                groupName: '92140',
              },
              {
                id: '6',
                name: '92145',
                length: 800,
                width: 1200,
                height: 1000,
                weight: 86.0,
                quantity: 1,
                cargoStyle: 1,
                rotatable: false,
                stackable: false,
                selfStackable: false,
                color: 'AD292C',
                maxLayer: 0,
                groupId: '6',
                groupName: '92145',
              },
              {
                id: '3',
                name: '92144',
                length: 500,
                width: 320,
                height: 460,
                weight: 10.0,
                quantity: 2,
                cargoStyle: 0,
                rotatable: false,
                stackable: true,
                selfStackable: false,
                color: '7aa8d5',
                maxLayer: 0,
                groupId: '3',
                groupName: '92144',
              },
              {
                id: '21',
                name: '92295',
                length: 1200,
                width: 800,
                height: 600,
                weight: 618.34,
                quantity: 3,
                cargoStyle: 1,
                rotatable: false,
                stackable: false,
                selfStackable: true,
                color: '507BD0',
                maxLayer: 2,
                groupId: '15',
                groupName: '92295',
              },
            ],
          },
        },
      ],
      config: {
        cargoSupport: 75,
        lightUnstackableWeightLimit: 105.0,
        allowHeavierCargoOnTop: false,
        maxHeavierCargoOnTop: 0.0,
        keepGroupsTogether: true,
        maxWeightDiffInPercent: 0.0,
        maxWeightDiffInKilos: 0.0,
      },
      groups: [
        {
          id: '4',
          name: '92131',
          items: [
            {
              id: '4',
              name: '92131',
              length: 800,
              width: 1000,
              height: 1480,
              weight: 87.0,
              quantity: 1,
              cargoStyle: 1,
              rotatable: false,
              stackable: false,
              selfStackable: false,
              color: '75c273',
              maxLayer: 0,
              groupId: null,
              groupName: null,
            },
          ],
          color: null,
          stackGroupOnly: false,
          alreadyLoaded: true,
          groups: null,
        },
        {
          id: '5',
          name: '92153',
          items: [
            {
              id: '5',
              name: '92153',
              length: 800,
              width: 1200,
              height: 2100,
              weight: 278.2,
              quantity: 10,
              cargoStyle: 1,
              rotatable: false,
              stackable: false,
              selfStackable: false,
              color: 'F49698',
              maxLayer: 0,
              groupId: null,
              groupName: null,
            },
          ],
          color: null,
          stackGroupOnly: false,
          alreadyLoaded: true,
          groups: null,
        },
        {
          id: '8',
          name: '91083',
          items: [
            {
              id: '8',
              name: '91083',
              length: 1800,
              width: 800,
              height: 1200,
              weight: 200.0,
              quantity: 1,
              cargoStyle: 1,
              rotatable: false,
              stackable: false,
              selfStackable: false,
              color: '63F563',
              maxLayer: 0,
              groupId: null,
              groupName: null,
            },
            {
              id: '9',
              name: '91083',
              length: 2100,
              width: 700,
              height: 1400,
              weight: 230.0,
              quantity: 1,
              cargoStyle: 1,
              rotatable: false,
              stackable: false,
              selfStackable: false,
              color: 'f6c41b',
              maxLayer: 0,
              groupId: null,
              groupName: null,
            },
          ],
          color: null,
          stackGroupOnly: false,
          alreadyLoaded: true,
          groups: null,
        },
        {
          id: '10',
          name: '91315',
          items: [
            {
              id: '12',
              name: '91315',
              length: 1200,
              width: 1200,
              height: 980,
              weight: 950.0,
              quantity: 3,
              cargoStyle: 1,
              rotatable: false,
              stackable: false,
              selfStackable: false,
              color: '07D380',
              maxLayer: 0,
              groupId: null,
              groupName: null,
            },
          ],
          color: null,
          stackGroupOnly: false,
          alreadyLoaded: true,
          groups: null,
        },
        {
          id: '11',
          name: '92256',
          items: [
            {
              id: '13',
              name: '92256',
              length: 800,
              width: 1200,
              height: 1160,
              weight: 341.67,
              quantity: 6,
              cargoStyle: 1,
              rotatable: false,
              stackable: false,
              selfStackable: false,
              color: 'b97fcf',
              maxLayer: 0,
              groupId: null,
              groupName: null,
            },
          ],
          color: null,
          stackGroupOnly: false,
          alreadyLoaded: true,
          groups: null,
        },
        {
          id: '12',
          name: '92309',
          items: [
            {
              id: '14',
              name: '92309',
              length: 2500,
              width: 1000,
              height: 1250,
              weight: 1200.0,
              quantity: 1,
              cargoStyle: 1,
              rotatable: false,
              stackable: true,
              selfStackable: false,
              color: '57f3c5',
              maxLayer: 0,
              groupId: null,
              groupName: null,
            },
          ],
          color: null,
          stackGroupOnly: false,
          alreadyLoaded: true,
          groups: null,
        },
        {
          id: '14',
          name: '91548',
          items: [
            {
              id: '19',
              name: '91548',
              length: 800,
              width: 1200,
              height: 650,
              weight: 174.0,
              quantity: 1,
              cargoStyle: 1,
              rotatable: false,
              stackable: true,
              selfStackable: false,
              color: 'F0EEA0',
              maxLayer: 0,
              groupId: null,
              groupName: null,
            },
            {
              id: '20',
              name: '91548',
              length: 800,
              width: 1200,
              height: 900,
              weight: 200.0,
              quantity: 1,
              cargoStyle: 1,
              rotatable: false,
              stackable: false,
              selfStackable: false,
              color: '7938d6',
              maxLayer: 0,
              groupId: null,
              groupName: null,
            },
          ],
          color: null,
          stackGroupOnly: false,
          alreadyLoaded: true,
          groups: null,
        },
        {
          id: 'C1',
          name: 'C1',
          items: [],
          color: null,
          stackGroupOnly: false,
          alreadyLoaded: true,
          groups: [
            {
              id: '1',
              name: '92140',
              items: [
                {
                  id: '1',
                  name: '92140',
                  length: 1200,
                  width: 800,
                  height: 670,
                  weight: 122.0,
                  quantity: 1,
                  cargoStyle: 1,
                  rotatable: false,
                  stackable: true,
                  selfStackable: false,
                  color: 'FFE5E9',
                  maxLayer: 0,
                  groupId: null,
                  groupName: null,
                },
              ],
              color: null,
              stackGroupOnly: false,
              alreadyLoaded: false,
              groups: null,
            },
            {
              id: '2',
              name: '92141',
              items: [
                {
                  id: '2',
                  name: '92141',
                  length: 1200,
                  width: 800,
                  height: 900,
                  weight: 149.86,
                  quantity: 1,
                  cargoStyle: 1,
                  rotatable: false,
                  stackable: false,
                  selfStackable: false,
                  color: '20af1a',
                  maxLayer: 0,
                  groupId: null,
                  groupName: null,
                },
              ],
              color: null,
              stackGroupOnly: false,
              alreadyLoaded: false,
              groups: null,
            },
            {
              id: '3',
              name: '92144',
              items: [
                {
                  id: '3',
                  name: '92144',
                  length: 500,
                  width: 320,
                  height: 460,
                  weight: 10.0,
                  quantity: 2,
                  cargoStyle: 0,
                  rotatable: false,
                  stackable: true,
                  selfStackable: false,
                  color: '7aa8d5',
                  maxLayer: 0,
                  groupId: null,
                  groupName: null,
                },
              ],
              color: null,
              stackGroupOnly: false,
              alreadyLoaded: false,
              groups: null,
            },
            {
              id: '6',
              name: '92145',
              items: [
                {
                  id: '6',
                  name: '92145',
                  length: 800,
                  width: 1200,
                  height: 1000,
                  weight: 86.0,
                  quantity: 1,
                  cargoStyle: 1,
                  rotatable: false,
                  stackable: false,
                  selfStackable: false,
                  color: 'AD292C',
                  maxLayer: 0,
                  groupId: null,
                  groupName: null,
                },
              ],
              color: null,
              stackGroupOnly: false,
              alreadyLoaded: false,
              groups: null,
            },
          ],
        },
        {
          id: 'C2',
          name: 'C2',
          items: [],
          color: null,
          stackGroupOnly: false,
          alreadyLoaded: true,
          groups: [
            {
              id: '7',
              name: '92155',
              items: [
                {
                  id: '7',
                  name: '92155',
                  length: 1250,
                  width: 800,
                  height: 600,
                  weight: 640.0,
                  quantity: 2,
                  cargoStyle: 1,
                  rotatable: false,
                  stackable: false,
                  selfStackable: false,
                  color: 'a9adae',
                  maxLayer: 0,
                  groupId: null,
                  groupName: null,
                },
              ],
              color: null,
              stackGroupOnly: false,
              alreadyLoaded: false,
              groups: null,
            },
            {
              id: '15',
              name: '92295',
              items: [
                {
                  id: '21',
                  name: '92295',
                  length: 1200,
                  width: 800,
                  height: 600,
                  weight: 618.34,
                  quantity: 3,
                  cargoStyle: 1,
                  rotatable: false,
                  stackable: false,
                  selfStackable: true,
                  color: '507BD0',
                  maxLayer: 2,
                  groupId: null,
                  groupName: null,
                },
              ],
              color: null,
              stackGroupOnly: false,
              alreadyLoaded: false,
              groups: null,
            },
          ],
        },
        {
          id: 'C3',
          name: 'C3',
          items: [],
          color: null,
          stackGroupOnly: false,
          alreadyLoaded: true,
          groups: [
            {
              id: '9',
              name: '92276',
              items: [
                {
                  id: '10',
                  name: '92276',
                  length: 600,
                  width: 800,
                  height: 500,
                  weight: 38.0,
                  quantity: 1,
                  cargoStyle: 0,
                  rotatable: false,
                  stackable: false,
                  selfStackable: false,
                  color: 'e4467d',
                  maxLayer: 0,
                  groupId: null,
                  groupName: null,
                },
                {
                  id: '11',
                  name: '92276',
                  length: 560,
                  width: 720,
                  height: 590,
                  weight: 35.75,
                  quantity: 1,
                  cargoStyle: 0,
                  rotatable: false,
                  stackable: false,
                  selfStackable: false,
                  color: 'af158d',
                  maxLayer: 0,
                  groupId: null,
                  groupName: null,
                },
              ],
              color: null,
              stackGroupOnly: false,
              alreadyLoaded: false,
              groups: null,
            },
            {
              id: '13',
              name: '92287',
              items: [
                {
                  id: '15',
                  name: '92287',
                  length: 5300,
                  width: 1050,
                  height: 1100,
                  weight: 800.0,
                  quantity: 1,
                  cargoStyle: 1,
                  rotatable: false,
                  stackable: true,
                  selfStackable: false,
                  color: 'C4D210',
                  maxLayer: 0,
                  groupId: null,
                  groupName: null,
                },
                {
                  id: '16',
                  name: '92287',
                  length: 1200,
                  width: 800,
                  height: 600,
                  weight: 295.97,
                  quantity: 1,
                  cargoStyle: 1,
                  rotatable: false,
                  stackable: true,
                  selfStackable: false,
                  color: '3CAFBE',
                  maxLayer: 0,
                  groupId: null,
                  groupName: null,
                },
                {
                  id: '17',
                  name: '92287',
                  length: 4200,
                  width: 800,
                  height: 800,
                  weight: 650.0,
                  quantity: 1,
                  cargoStyle: 1,
                  rotatable: false,
                  stackable: true,
                  selfStackable: false,
                  color: 'F66718',
                  maxLayer: 0,
                  groupId: null,
                  groupName: null,
                },
                {
                  id: '18',
                  name: '92287',
                  length: 5300,
                  width: 500,
                  height: 900,
                  weight: 700.0,
                  quantity: 1,
                  cargoStyle: 1,
                  rotatable: false,
                  stackable: true,
                  selfStackable: false,
                  color: 'BE9FEB',
                  maxLayer: 0,
                  groupId: null,
                  groupName: null,
                },
              ],
              color: null,
              stackGroupOnly: true,
              alreadyLoaded: false,
              groups: null,
            },
            {
              id: '16',
              name: '92234',
              items: [
                {
                  id: '22',
                  name: '92234',
                  length: 800,
                  width: 1100,
                  height: 620,
                  weight: 215.0,
                  quantity: 1,
                  cargoStyle: 1,
                  rotatable: false,
                  stackable: false,
                  selfStackable: false,
                  color: 'BAB5F5',
                  maxLayer: 0,
                  groupId: null,
                  groupName: null,
                },
              ],
              color: null,
              stackGroupOnly: false,
              alreadyLoaded: false,
              groups: null,
            },
          ],
        },
        {
          id: 'C4',
          name: 'C4',
          items: [],
          color: null,
          stackGroupOnly: false,
          alreadyLoaded: true,
          groups: [
            {
              id: '17',
              name: '92252',
              items: [
                {
                  id: '23',
                  name: '92252',
                  length: 2500,
                  width: 900,
                  height: 1300,
                  weight: 372.0,
                  quantity: 1,
                  cargoStyle: 1,
                  rotatable: false,
                  stackable: false,
                  selfStackable: false,
                  color: 'd7f4b2',
                  maxLayer: 0,
                  groupId: null,
                  groupName: null,
                },
              ],
              color: null,
              stackGroupOnly: false,
              alreadyLoaded: false,
              groups: null,
            },
            {
              id: '18',
              name: '92253',
              items: [
                {
                  id: '24',
                  name: '92253',
                  length: 1900,
                  width: 1200,
                  height: 1100,
                  weight: 200.0,
                  quantity: 1,
                  cargoStyle: 1,
                  rotatable: false,
                  stackable: false,
                  selfStackable: false,
                  color: 'f6dc7a',
                  maxLayer: 0,
                  groupId: null,
                  groupName: null,
                },
              ],
              color: null,
              stackGroupOnly: false,
              alreadyLoaded: false,
              groups: null,
            },
          ],
        },
      ],
      status: 0,
    };
  }
}
